### ISSUE TITLE
Sector alarm Norway

### ISSUE THREAD

**Issue by GunnarBjoru** [gjohansson-ST/sector#1]
I haven't tried but is there any reason this would not work for Sector alarm in Norway?

**Comment by gjohansson-ST** [comment]
No. As far as I know it’s all the same platform/api

**Comment by GunnarBjoru** [comment]
My first attempt was not successful. Maybe i did somethings wrong.
Isn't the **alarm_id** number required?

**Comment by gjohansson-ST** [comment]
Hi.
No, it finds the panel id itself from login. 
Can you turn on debug for sector and restart and check the log file (search for “sector”) where it should report where it goes wrong. 
Maybe also do a check that the credentials you put in config really works if you login on sector homepage.

**Comment by yusijs** [comment]
I've set it up for Norway as well. I got an id and it looks ok (I think?), but state is always pending, with this information:

code_format: '^\d{4,6}$
changed_by: null
code_arm_required: true
supported_features: 3
friendly_name: Sector Alarm 12345678

(12345678 is obv not the actual value, just placeholder for this comment.. 🙃)

**Comment by gjohansson-ST** [comment]
Any error in the log file or even better can you turn on debug for this component?
Search for “sector” until you see an error. 
Do you have last version installed?
Do you use temp sensors and locks?

**Comment by yusijs** [comment]
I set debug, I could only find one thing:
2020-06-07 15:50:31 DEBUG (MainThread) [custom_components.sector] Sector: Failed to get locks update: 500

It gets a good response from the IR sensors (temperatur etc). The only error I was able to find was the 500 status. I installed it today so I would assume it's the latest version. I use temp sensor & alarm, not locks.

**Comment by gjohansson-ST** [comment]
Ok. Then I have a good guess what’s incorrect in the update function. 
Will sort it tonight and then make a comment here when I released a new version. 
Thanks

Don’t forget to turn off the debug :)

**Comment by yusijs** [comment]
Yep, turning off now! :)

**Comment by gjohansson-ST** [comment]
I did just release a bet which should address this issue.
Please switch to allow beta in the integration and install the new v0.1.6-beta version.
Please let me know if it's working after install and reboot.

**Comment by yusijs** [comment]
Installed, worked perfectly now. I havent tried arming it (just put the kids to bed), but the status is correct!

![image](https://user-images.githubusercontent.com/11261560/83976750-4751f580-a8fc-11ea-82be-24db26a2295b.png)

**Comment by gjohansson-ST** [comment]
> Installed, worked perfectly now. I havent tried arming it (just put the kids to bed), but the status is correct!
> 
> ![image](https://user-images.githubusercontent.com/11261560/83976750-4751f580-a8fc-11ea-82be-24db26a2295b.png)

Cool. Thanks for confirming. I close this issue now. If anything please raise a new issue ticket

**Comment by yusijs** [comment]
@gjohansson-ST wasnt solved after all - I tried arming today, and it failed because "lock is not defined"
