### ISSUE TITLE
async_get_registry deprecated

### ISSUE THREAD

**Issue by frli4797** [gjohansson-ST/sector#102]
**Describe the bug**
Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom integration author for sector using this method at custom_components/sector/__init__.py, line 135: device_registry = await dr.async_get_registry(hass)

**Version**
Sector 0.34
Homeassistant 2022.08.7

**Expected behavior**
No usage of deprecated code. 

**Additional context**

**Comment by gjohansson-ST** [comment]
Has been fixed earlier and will be in next release

**Comment by gjohansson-ST** [comment]
Solved with https://github.com/gjohansson-ST/sector/releases/tag/v0.3.5
