### ISSUE TITLE
Can't take v0.3.5-beta11 into use

### ISSUE THREAD

**Issue by jlatvala** [gjohansson-ST/sector#111]
Upgraded to beta 11 and after that integration is not working anymore.
Also the initial setup, after deleting and reinstalling integration doesn't work.

Waited overnight, and no success.

Also devices/entities are not available after (failing) setup.

Initial setup was working in earlier beta versions
 
Log:
Config entry 'someuser@email.com' for sector integration not ready yet: Could not retrieve panel; Retrying in background

I am using Finnish Sector Alarm.

I have also noticed that earlier Sector Alarm's login page was in
https://omatsivut.sectoralarm.fi/User/Login#!/
and now it is in
https://login.sectoralarm.com/login?state=...
(don't know when Sector Alarm has changed this)

**Comment by gjohansson-ST** [comment]
`coordinator.py` has been updated with fixes. Please replace this file on your local system to test [coordinator](https://github.com/gjohansson-ST/sector/blob/master/custom_components/sector/coordinator.py)

**Comment by gjohansson-ST** [comment]
Solved with https://github.com/gjohansson-ST/sector/releases/tag/v0.3.5
