### ISSUE TITLE
Retrying setup: Could not retrieve panel

### ISSUE THREAD

**Issue by zucram** [gjohansson-ST/sector#114]
**Describe the bug**
Can’t get the integration up and running. Reports Retrying setup: Could not retrieve panel. It has been working fine before except for needing to reauth a lot. Have tried uninstalling and reinstalling but no difference

**Version**
Latest version

**Comment by gjohansson-ST** [comment]
Trying to solve the last bits and pieces so we can release a new working version.
See progress in #100

**Comment by zucram** [comment]
Great! Thanks for quick reply! Hoping it will be fixed soon then!

**Comment by zucram** [comment]
Any progress on this? Reauthing was irritating but manageable but now I can't get the integration working at all.

**Comment by gjohansson-ST** [comment]
Trying to resolve the last bits and pieces.

**Comment by gjohansson-ST** [comment]
Solved with https://github.com/gjohansson-ST/sector/releases/tag/v0.3.5
