### ISSUE TITLE
Local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by jlatvala** [gjohansson-ST/sector#125]
Logger: custom_components.sector
Source: custom_components/sector/coordinator.py:389
Integration: Sector Alarm ([documentation](https://github.com/gjohansson-ST/sector/blob/master/readme.md), [issues](https://github.com/gjohansson-ST/sector/issues))
First occurred: 08:16:36 (**12 occurrences**)
Last logged: 12:57:52

Unexpected error fetching sector data: local variable 'response' referenced before assignment
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/sector/coordinator.py", line 233, in _async_update_data
    response_get_status = await self._request(
  File "/config/custom_components/sector/coordinator.py", line 389, in _request
    if response.status == 401:
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by gjohansson-ST** [comment]
I don't see how this is even possible...

**Comment by gjohansson-ST** [comment]
Correction, I see how this is possible. Will release a new version asap.
