### ISSUE TITLE
Mask PIN from log entries

### ISSUE THREAD

**Issue by jlatvala** [gjohansson-ST/sector#132]
Maybe (at least) the PIN/passcode (see "abcd" below) should be masked from all log entries (e.g. mask it with ****)?

---

Logger: custom_components.sector
Source: custom_components/sector/coordinator.py:122
Integration: Sector Alarm (documentation, issues)
First occurred: 11:54:44 (2 occurrences)
Last logged: 11:54:55

Timeout during fetching https://mypagesapi.sectoralarm.net/api/Panel/Disarm with data {'PanelCode': 'abcd', 'PanelId': '12345678', 'Platform': 'app'}

**Comment by gjohansson-ST** [comment]
Good point. Currently it spits out all the raw data on such failures. I will look it through also in the other data points to mask it.
