### ISSUE TITLE
Feature request: add doors and windows sensor status

### ISSUE THREAD

**Issue by TorStava** [gjohansson-ST/sector#137]
Since this information is available in the Android app and on the website, I figured it should be available in the API. 

And so it is:

Endpoint: https://mypagesapi.sectoralarm.net/api/housecheck/doorsandwindows
and: https://mypagesapi.sectoralarm.net/api/v2/housecheck/doorsandwindows

(I assume they will move to API v2 in the future)

Sending a POST request with "panelId": PANELID payload returns the devices registered for each floor and room.
Headers were the same as the other requests (including the Authorization token).

I would have given it a try to implement it myself, but my time is already stretched too thin.

**Comment by gjohansson-ST** [comment]
As the integration is getting a huge overhaul I'm going to close this issue.
We can create a new one if the problem exist after next release.
