### ISSUE TITLE
Feature request: Add smoke detector status

### ISSUE THREAD

**Issue by TorStava** [gjohansson-ST/sector#138]
The endpoint for smoke detectors is:

https://mypagesapi.sectoralarm.net/api/v2/housecheck/smokedetectors
(and https://mypagesapi.sectoralarm.net/api/housecheck/smokedetectors)

Accessed with POST request and "paneId": PANELID payload

Also ref. #137

**Comment by gjohansson-ST** [comment]
As the integration is getting a huge overhaul I'm going to close this issue.
We can create a new one if the problem exist after next release.
