### ISSUE TITLE
lock.lock and lock.unlock no longer working

### ISSUE THREAD

**Issue by TomTorger** [gjohansson-ST/sector#14]
This worked a couple of weeks ago (doorman v2), but now it no longer works.
    - type: glance
            #(...)
            entities:
              - entity: lock.ytterdor
                name: Ytterdør
                tap_action:
                  action: call-service
                  service: lock.lock
                  service_data:
                    entity_id: lock.ytterdor
                    code: !secret sector_code

**Comment by klercker** [comment]
I just tried my locks with 0.2.0 (re-installed via new configuration flow UI) and it worked well for my doorman v2.

**Comment by TomTorger** [comment]
Ah... I had it installed via HACS.

I tried to uninstall it and re-install via the the new configuration flow UI, but I am not able to install it... I'm at 0.117.5 will try to pull the latest release.

**Comment by klercker** [comment]
You still install via HACS, but then you add the config through the UI.

**Comment by TomTorger** [comment]
Yup, re-read the read-me and I've now got it configured via the ui :-)

However, no cigar on the lock. Temperature sensors show up fine. Works fine in the app...

**Comment by TomTorger** [comment]
The app version is v2.0.22... Don't know if that matters :-)

**Comment by gjohansson-ST** [comment]
I have had this myself that it works and then suddenly it does not work.
But then it does not work from the Sector Alarm app either so I think in general it's something with the backend of Sector but couldn't confirm that being the case.

**Comment by SeilinHa** [comment]
same problem here, everything else works fine, but not the Lock / unlock Yale doorman V2...

**Comment by gjohansson-ST** [comment]
> same problem here, everything else works fine, but not the Lock / unlock Yale doorman V2...

Do we know if this worked without failures before this integration was installed in HA?
I am personally not using it neither before or after I did this integration.
I am wondering if this is a SA problem in general or if this is really due to this integration.

**Comment by SeilinHa** [comment]
I have only tested this integration now, before I have only used the regular app from Sector and controlled the lock that way.
I do not know if I do anything wrong or not.

This is how my card looks like 
![yale](https://user-images.githubusercontent.com/75683144/101608025-85dc8000-3a05-11eb-8941-27507d712132.jpg)

**Comment by gjohansson-ST** [comment]
> I have only tested this integration now, before I have only used the regular app from Sector and controlled the lock that way.
> I do not know if I do anything wrong or not.
> 
> This is how my card looks like
> 
> it seems to registry that the lock has been opened, etc. manually

And you mean before using this integration unlocking/locking the door was ok without issues?
Do you have autolock enabled or not?

**Comment by SeilinHa** [comment]
> And you mean before using this integration unlocking/locking the door was ok without issues?
> Do you have autolock enabled or not?

Yes, before it was OK without any issues. Yes, Autolock is enabled.

**Comment by gjohansson-ST** [comment]
Can you check if this is still the case using the newest beta v0.2.2-beta1

**Comment by SeilinHa** [comment]
Tested a while ago and it's the same problem, nothing happens.
and I think I'm doing that correctly, to enter the passcode that I usually enter on the keypad, in the "code / kod" field, and then click "unlock / lås upp". 
I liked the keypad for on and off alarm :)

**Comment by TomTorger** [comment]
Still the same. I tried to have a look at it a while back and did some digging in the code. It appears as if it stems from the underlying library and the  json sent to the server. There is no action on the server side even though the json appears correct. Might be that they change the format now and then? Could be the reason for the versioning? I also saw that there were different servers to choose from...

In the end I gave up. I think I would have to look at the json sent by the app to get further. And I might be wrong in some of my "observations" above 😊

**Comment by gjohansson-ST** [comment]
Just released new beta (beta2) addressing this. Seems to work fine for me right now with some minor tests.
I am using autolock so it unlocks without making a sound and then locks again shortly after with the distinctive lock sound.
Give it a try and let me know.

**Comment by SeilinHa** [comment]
Woks like a charm, nice work!

**Comment by TomTorger** [comment]
Yes, works. Just works :-) Out of curiosity, what was the issue?

**Comment by gjohansson-ST** [comment]
> Out of curiosity, what was the issue?

There were a few actually so let's just say I didn't review it properly before 😄

**Comment by gjohansson-ST** [comment]
Closed with v0.3.0
