### ISSUE TITLE
Integration stuck in "Pending"

### ISSUE THREAD

**Issue by riborg** [gjohansson-ST/sector#141]
**Describe the bug**
The integration is still stuck in "Pending" state.
Debug log says it's not online..
```
Retreived Panel status {'IsOnline': False, 'StatusTime': '2022-10-12T14:35:21', 'Status': 1, 'AnnexStatus': 0}
```

**Version**
HA 2022.10.5
Sector 0.3.8

**Expected behavior**
Integration should go online.

**Comment by kristianwh** [comment]
I have had this issue for a few weeks also. Tried 11.1 today, same issue.

**Comment by kristianwh** [comment]
That was fast. Thanks!
