### ISSUE TITLE
Attribute changed_by not updated on state change

### ISSUE THREAD

**Issue by hnrkgrln** [gjohansson-ST/sector#146]
**Describe the bug**
The changed_by attribute doesn't reflect the state of the alarm. Trigger data shows correct state changes except on change_by attribute which keeps the previous state.

This means that automations triggered on changed_by or that uses changed_by aren't working as expected.

**Version**
v0.3.9

**Expected behavior**
changed_by attribute should reflect the current state of the alarm on state change.

**Additional context**
The changed by shows the correct value in the Sector Alarm app history.

Example from automation trace:

>
trigger:
...
  platform: state
  entity_id: alarm_control_panel.sector_alarmpanel_xxx
  from_state:
    entity_id: alarm_control_panel.sector_alarmpanel_xxx
    state: armed_away
    attributes:
      code_format: number
      changed_by: Hemfrid **<<CORRECT**
      code_arm_required: false
      display_name: xxx
      friendly_name: Sector Alarmpanel xxx
      supported_features: 3
    last_changed: '2022-11-18T12:58:05.030076+00:00'
    last_updated: '2022-11-18T12:58:05.030076+00:00'
...
  to_state:
    entity_id: alarm_control_panel.sector_alarmpanel_xxx
    state: disarmed
    attributes:
      code_format: number
      changed_by: Hemfrid **<<INCORRECT**
      code_arm_required: false
      display_name: xxx
      friendly_name: Sector Alarmpanel xxx
      supported_features: 3
    last_changed: '2022-11-18T13:26:45.949567+00:00'
    last_updated: '2022-11-18T13:26:45.949567+00:00'
...

**Comment by gjohansson-ST** [comment]
As the integration is getting a huge overhaul I'm going to close this issue.
We can create a new one if the problem exist after next release.
