### ISSUE TITLE
Integration overusing API?

### ISSUE THREAD

**Issue by klercker** [gjohansson-ST/sector#15]
Hi, thanks for the great integration! Given the level of support from SA, it's amazing we can do as much as we can with the SA/HA combo.

In the logs I can see that the integration is calling the SA "apis" roughly once a minute or more. There are also plenty warnings that sensor updates are taking too long etc. I have in the past had my SA account locked due to the integration calling too many times - within some given time slot I presume. SA is from what I understand known for not being super generous with their APIs.

What is being done to throttle API calls in the integration under various circumstances? Is this a problem for more people than me? My Python (and knowledge of Python libraries/apis) is not quite good enough to be able to understand this from the code. There are high level helpers built into HA that seem to help address such issues (https://developers.home-assistant.io/docs/integration_fetching_data).

Thoughts?

**Comment by gjohansson-ST** [comment]
Throttling are implemented on the update so it will call the api every 60 seconds for updating data, no more, no less.
If you call the api for locking, alarming etc. it goes instantly to the api for such (which I would personally prefer).

In general with SA it seems 60 seconds are fine for them not to lock your account unless you would hammer them with alarming, locking updates and personally has not had an issue for a long time as I implemented this restriction in update throttling.

The "complaint" normally comes from the temp-sensors which are responding from the api very slow (for whatever reason). I could change so those are restricted to every 5 minutes or so instead as per minute is not necessarily needed.

What do you think?

**Comment by klercker** [comment]
All sounds reasonable to me. The restricting sensors further also seems like a good idea. It could be an idea to have the polling limits configurable (with current values as default), so that any "changes in service level" from SA can be adjusted to without a new release.

**Comment by gjohansson-ST** [comment]
I guess for the sensors it makes sense to reduce the updating but for alarm and locks I guess you want as quick response as possible so I would think to keep those on 60 seconds but then implement more like 5 minutes for the slow sensors. I think possibly those would be the ones who puts pressure on the api in this case as retrieving info for alarm and locks goes very quick in response from the api.

**Comment by gjohansson-ST** [comment]
https://github.com/gjohansson-ST/sector/releases/tag/v0.2.1-beta1
Not tested

**Comment by gjohansson-ST** [comment]
beta1 not working. Beta 2 released. This one tested
https://github.com/gjohansson-ST/sector/releases/tag/v0.2.1-beta2

**Comment by gjohansson-ST** [comment]
Will close this as the limitation is on SA's side and their api. Especially when it comes to temp-sensors which are horrible to update
