### ISSUE TITLE
Support for numeric code format

### ISSUE THREAD

**Issue by klercker** [gjohansson-ST/sector#16]
Hi!

I use the alarm control panel card (as I assume many others?), which works, but I never got the numeric keyboard, only an input which when in focus gives me the standard keyboard (not great for inputting numbers). Is anybody else seeing this problem? 

Looking at the source code for the card (https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/cards/hui-alarm-panel-card.ts), it looks at the code_format property of the panel, if it's FORMAT_NUMBER (as defined in the alarm_control_panel platform(?)), it will display the numeric pad, otherwise not. For me: not. A bit of digging in the sector code told me that this property value is being set, but I can't quite make out how.

To my knowledge, the code can't be anything but numeric in Sector, so at least having the option to hard-set this myself to numeric or have the integration do this directly would be awesome. It would make the useability of the integration even better. 

Or, this could of course be SBS (skit bakom styret) and it's my own error altogether. Cheers/Måns

**Comment by gjohansson-ST** [comment]
Addressed in version v0.2.2-beta1
Works in test so please confirm

**Comment by klercker** [comment]
Okelidok, time for a dip in beta waters...

**Comment by gjohansson-ST** [comment]
Closed with v0.3.0
