### ISSUE TITLE
suddenly sending wrong status

### ISSUE THREAD

**Issue by strelniece** [gjohansson-ST/sector#17]
Not quite sure whats going on and haven''t found any way to figure outeither.

But every once in a while the status will change from home to away in home assistant. And then back to home.

The problem is that I have an automation that is triggered when the alarm changes to away. You know, like turning off all lights, media, heat... 

Any idea what's going on? 

I guess an easy solution to the problem is to add one more trigger, like check if phone is home, but would prefer not to.

**Comment by gjohansson-ST** [comment]
Hi
This does not seem accurate as I have been running this for a very long time and have had nothing comparable to what you describe.
I suggest you check your logbook and see it's not another automation or anything that switch your alarm on. You don't happen to have an automation that turns the alarm on when your phone leaves i.e. "not_home" and therefore it's not this integration, instead it's whatever you use as device_tracker for your phone?

**Comment by strelniece** [comment]
Hej, 

Gissar jag rätt att du kan svenska? ;) 

Själva larmet triggas inte, utan bara statusen i homeassistant. Och sedan så går den tillbaka till avlarmat nån minut senare. 

Den enda automationen jag har där larmet i sig påverkas är skalskydd på när jag går och lägger mig. 

Däremot så triggar då bortaläget automationen där då allt släcks... Men då ingen som sätter larmet i bortaläget. 

Så finns liksom ingen anledning till att det ska hända. Och hittar inget i loggarna heller. 

Nu händer det inte jätteofta, men irriterande när det väl händer... 

⁣Skaffa BlueMail för Android ​


-------- Ursprungligt meddelande --------
Från: G Johansson <notifications@github.com>
Skickat: Sun Dec 20 11:56:51 GMT+01:00 2020
Till: gjohansson-ST/sector <sector@noreply.github.com>
Cc: strelniece <blandat@schuetz.se>, Author <author@noreply.github.com>
Ämne: Re: [gjohansson-ST/sector] suddenly sending wrong status (#17)

Hi
This does not seem accurate as I have been running this for a very long time and have had nothing comparable to what you describe.
I suggest you check your logbook and see it's not another automation or anything that switch your alarm on. You don't happen to have an automation that turns the alarm on when your phone leaves i.e. "not_home" and therefore it's not this integration, instead it's whatever you use as device_tracker for your phone?

**Comment by gjohansson-ST** [comment]
Om larmet ändrar status (vad det nu skulle vara för anledning) så bör det skrivas i HA's logbok.
Den har du på vänstersidan i navigatorn.
Kan du ta fram din entitet för larmet i den och sätter tiden ordentligt så bör det stå där vad som har hänt.
Exempel bifogat från mitt system
![2020-12-22_17-41-29](https://user-images.githubusercontent.com/62932417/102911946-12af2100-447d-11eb-9c25-a2bd037fdea7.jpg)

**Comment by gjohansson-ST** [comment]
Jag vet inte om du fortfarande upplever problemet men om inte annat så stänger jag ärendet om ett par dagar såvida du inte kan tillföra mer info

**Comment by gjohansson-ST** [comment]
Closed as per no reply and can not confirm any bug
