### ISSUE TITLE
Setting up connection with temp sensors fail

### ISSUE THREAD

**Issue by ronnybs** [gjohansson-ST/sector#171]
**Describe the bug**
Signing up a the integration with the temp readings true. Reports error

**Version**
Core
2023.11.3
Supervisor
2023.11.3
Operating System
11.1
Frontend
20231030.2

**Expected behavior**
Get the enteties with temperature readings

**Additional context**

Logger: custom_components.sector
Source: helpers/update_coordinator.py:290
Integration: Sector Alarm (documentation, issues)
First occurred: 22:58:51 (7 occurrences)
Last logged: 23:03:55

Unexpected error fetching sector data: 'xxxxx'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sector/coordinator.py", line 266, in _async_update_data
    data[key]["temp"][serial]["temperature"] = temp.get(
    ~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'xxxxxxx'

**Comment by gjohansson-ST** [comment]
As the integration is getting a huge overhaul I'm going to close this issue.
We can create a new one if the problem exist after next release.
