### ISSUE TITLE
Need to reconfigure after 24h

### ISSUE THREAD

**Issue by Xoooppzz** [gjohansson-ST/sector#173]
**Describe the bug**
The integration stops working after 24h. Then I need to reconfigure and login again to sector Alarm. Then it works for another 24h and then reconfigure/re-auth for another 24h. Endless loop. 
Integration is not storing the credentials? 

**Version**
0.4.3

**Expected behavior**
Not have re-authenticate/relogin to sector Alarm more than one time. 

**Additional context**
Have tried to remove and re-install the integration. Not using any temp sensors.

**Comment by phellarv** [comment]
Still the same problem, or even worse now. I have to re-authenticate every time I restart HA.
And re-authentication takes forever to complete.

**Comment by gjohansson-ST** [comment]
As the integration is getting a huge overhaul I'm going to close this issue.
We can create a new one if the problem exist after next release.
