### ISSUE TITLE
New alarm system from Sector does not show alarm status

### ISSUE THREAD

**Issue by Henke19822** [gjohansson-ST/sector#176]
**Describe the bug**
I installed the new Sector Alarm system in my new house, but no entity shows what alarm status that is active. Some entities seems "broken"
**Version**
0.4.3

**Expected behavior**
A entity that shows if the alarm is armed or not

**Additional context**
N/A
![sector](https://github.com/gjohansson-ST/sector/assets/48420440/eee33460-a272-468b-8417-82699b252d15)

**Comment by klercker** [comment]
I believe the Alarm panel status is the indicator of whether the alarm is armed or not (I think this is how the alarm integration defines things). There are some broken entities though that perhaps should be looked at?

**Comment by Henke19822** [comment]
Yea, I believe you are correct. But that entity is "unactivated by configuration".
![SmartSelect_20240710_153125_Home Assistant](https://github.com/gjohansson-ST/sector/assets/48420440/a9116296-0809-48bb-a406-37111253e1bf)

**Comment by gjohansson-ST** [comment]
As the integration is getting a huge overhaul I'm going to close this issue.
We can create a new one if the problem exist after next release.
