### ISSUE TITLE
Sorry but not an issue, more lack of knowledge

### ISSUE THREAD

**Issue by lawi75** [gjohansson-ST/sector#18]
I have been trying back and forth to get a notification when alarm is in home mode (skalskydd)... I'm trying to turn on a light when the alarm is armed but I don't get any triggers?

- id: 'xxx'
  alias: Skalskydd
  description: Skalskyddet är påslaget
  trigger:
  - platform: state
    entity_id: alarm_control_panel.sector_alarmpanel_02648684
    to: 'on'
  condition: []
  action:
  - service: notify.notify
    data:
      message: bla bla
      title: bla bla bla
  mode: single

Also tried this:

- id: 'xxx'
  alias: Skalskydd
  description: Skalskyddet är påslaget
  trigger:
  - platform: state
    device_id: c878c1b63ac577ea1f6377951e8ee0c2
    domain: alarm_control_panel
    entity_id: alarm_control_panel.sector_alarmpanel_02648684
    type: armed_home
  condition: []
  action:
  - service: notify.notify
    data:
      message: bla bla
      title: bla bla bla
  mode: single

**Comment by gjohansson-ST** [comment]
In your trigger the to is a selection of these
- disarmed
- armed_home
- armed_away

If your automations looks as you have posted them it will not work as a service to send notification can not be in the trigger section, has to be as an action

**Comment by lawi75** [comment]
Thx :-) Now I figured it out
