### ISSUE TITLE
Keypad and arm / arm home gone

### ISSUE THREAD

**Issue by SeilinHa** [gjohansson-ST/sector#19]
Updated to latest beta version, Last update: v0.3.0-beta3 and now the Keypad and arm / arm home are gone.

**Comment by gjohansson-ST** [comment]
Is the entity at all active if you look in developer tools?

**Comment by SeilinHa** [comment]
It says unavailable for the alarm panel.

**Comment by gjohansson-ST** [comment]
I would be pretty sure you have some errors in the log-file.
Can you submit them here?

**Comment by SeilinHa** [comment]
First occurred: 13:59:14 (2 occurrences)
Last logged: 14:50:51

Error while setting up sector platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/sector/alarm_control_panel.py", line 40, in async_setup_entry
    SectorAlarmPanel(sector_hub, coordinator, code)
TypeError: __init__() missing 1 required positional argument: 'code_format'

**Comment by gjohansson-ST** [comment]
Thanks
I completely missed that one in my clean-up 😒 
I will release beta4 in a few minutes. Takes some time before HACS updates in your HA so give it a moment and then you will see it.
Let me know if it solves the issue

**Comment by SeilinHa** [comment]
Ah, great. Yes I will test that and get back to you =) Great feedback and support!
