### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lawi75** [gjohansson-ST/sector#21]
Hi,

Ones again the wrong way to communicate :-) Is there a way to ask questions etc on github?

My question is where/if I can find the documentation or more specifically is there any way for me to know who has turned off the alarm or even better unlocked the door?

**Comment by gjohansson-ST** [comment]
Hi
On the alarm entity there is an attribute "changed_by" which says who last changed the status of the alarm.
On the lock I have not done such attribute. If you want it there too then please raise a new issue for that specific so I can implement it.
I have not setup the "questions" section on github so it's ok if you raise issue for questions.

Let me know if it answers your question

**Comment by lawi75** [comment]
Tack... Funkar för mig... Vill tända alla lampor på max om det är städet som larmar av :-)

**Comment by gjohansson-ST** [comment]
Se till att du väntar en liten stund mellan avlarmning och du kollar vem som larmade av eftersom det kan ta en stund för api't att rapportera ordentligt. Lite tråkigt men tyvärr en begränsning att ta hänsyn till.
