### ISSUE TITLE
Not able to find it in Integrations when using Norwegian language

### ISSUE THREAD

**Issue by GunnarBjoru** [gjohansson-ST/sector#23]
After installing using HACS I was not able to add it from the list of integrations because it didn't show up.
But when I changed to English language I could see it in the integration list.
I have seen examples of this 'no' for Norway create problems with other things before.
It was no problem changing back to Norwegian language after setting up the integration.

**Comment by gjohansson-ST** [comment]
I have implemented a no language file so I believe this will sort the issue in the upcoming release
