### ISSUE TITLE
Account with many alarmsystems

### ISSUE THREAD

**Issue by MrJinxed55** [gjohansson-ST/sector#24]
I have 2 alarm systems on my app.

After a restart of HACS and home assistant, the Sector Alarm software changed to another alarm system.

So when trying to manage my house alarm, it switched on my restaurant alarm, really waking up my staff in the middle of their shift.

How do I choose which alarm system is accessible in this software?

**Comment by gjohansson-ST** [comment]
Do you know how to run a python file to provide me with the required output?

**Comment by marcfager** [comment]
Hi, just add ?panelid=123456 (where 123456 would be the correct system id that can be found by logging in with a browser). I.e. https://mypagesapi.sectoralarm.net/api/panel/getFullSystem?panelid=123456

**Comment by gjohansson-ST** [comment]
> Hi, just add ?panelid=123456 (where 123456 would be the correct system id that can be found by logging in with a browser). I.e. https://mypagesapi.sectoralarm.net/api/panel/getFullSystem?panelid=123456

Does it say somewhere on the sector website or does someone need to fish in the code to get hold of it?

**Comment by gjohansson-ST** [comment]
I would agree it seems easiest to make a non-mandatory option to use it but my question was mainly for a user how does he know his panel id. Is that on the sector website so it's possible for a "regular" user to fill it?

**Comment by marcfager** [comment]
Sorry, I misunderstood your question. Yes, it can be found without any special tools as per below:
1. Log in to https://mypagesapi.sectoralarm.net/
2. You are greeted by a list of the alarm systems you have. Hover with the pointer on the interesting one(s).
3. Check the URL for the numbers in the end. I.e. if the link is "https://mypagesapi.sectoralarm.net/#!/systems/12345678" your panel id is 12345678.

**Comment by gjohansson-ST** [comment]
Perfect!
I will create a beta for it after next release and hope you can try it out for me then.
Thanks so far

**Comment by marcfager** [comment]
I would be happy to do that! Can you write a comment here when the beta is ready? :)

**Comment by gjohansson-ST** [comment]
Will for sure let you know here when it's ready to test

**Comment by marcfager** [comment]
Hi, just wanted to follow up if you have had any opportunity to look at this yet? :)

**Comment by gjohansson-ST** [comment]
Not really unfortunately but let's try to get this sorted now.
Could you perhaps run this [file ](https://github.com/gjohansson-ST/sector/blob/master/api-info/api_info.py) and provide me with the output.
There is sensitive data in the output so you need to mask to what you feel comfortable with.

**Comment by marcfager** [comment]
Hi,

The code failed at the lock section (the setup does not have any logs). I declared the output variable to be printed just to allow it to run through. I have changed names and serials in the output. I also removed the log section in the end, as it only shows when the unit has been armed&disarmed.

```2022-06-08 22:15:13.148148
2022-06-08 22:15:13.744864
FULLSYSTEMINFO
{'Panel': {'PartialAvalible': True, 'PanelQuickArm': False, 'PanelCodeLength': 4, 'LockLanguage': 1, 'SupportsApp': True, 'SupportsInterviewServices': True, 'SupportsPanelUsers': True, 'SupportsTemporaryPanelUsers': True, 'SupportsRegisterDevices': True, 'CanAddDoorLock': False, 'CanAddSmartPlug': False, 'HasVideo': False, 'Wifi': {'WifiExist': False, 'Serial': ''}, 'PanelId': '01234567', 'ArmedStatus': 'partialarmed', 'PanelDisplayName': 'SuperSecretPanelName', 'StatusAnnex': 'unknown', 'PanelTime': '2022-06-08T21:43:38', 'AnnexAvalible': False, 'IVDisplayStatus': True, 'DisplayWizard': False, 'BookedStartDate': '0001-01-01T00:00:00', 'BookedEndDate': '0001-01-01T00:00:00', 'InstallationStatus': 3, 'InstallationAddress': None, 'WizardStep': 0, 'AccessGroup': 0, 'SessionExpires': '0001-01-01T00:00:00', 'IsOnline': True}, 'Locks': [], 'Smartplugs': [{'Consumption': None, 'DisplayScenarios': False, 'Id': '2345678', 'Label': 'SmartPlug', 'PanelId': None, 'SerialNo': '12345678901', 'Scenarios': None, 'Status': '', 'TimerActive': False, 'TimerEvents': None, 'TimerEventsSchedule': None}], 'Temperatures': [{'Id': None, 'Label': 'TemperatureLabel', 'SerialNo': '12345678901', 'Temprature': '', 'DeviceId': None}], 'Cameras': [], 'Photos': [], 'Access': ['History', 'Smartplugs']}
2022-06-08 22:15:14.029424
GetPanelStatus
{'IsOnline': True, 'StatusTime': '2022-06-08T21:43:38', 'Status': 2, 'AnnexStatus': 0}
2022-06-08 22:15:18.203378
GetTemperatures
[{'Id': None, 'Label': 'TemperatureLabel', 'SerialNo': '12345678901', 'Temprature': '25', 'DeviceId': None}]
2022-06-08 22:15:20.405684
Funkar inte
GetLockStatus

2022-06-08 22:15:20.724418
GetLogs```
