### ISSUE TITLE
Status is unexpectedly changed to 'Armed away'

### ISSUE THREAD

**Issue by perra123** [gjohansson-ST/sector#26]
Looks like the same issue as #17, the alarm status fetched from Sector is incorrectly read as 'Armed away' (the actual alarm was disarmed the entire time).
![image](https://user-images.githubusercontent.com/35863893/114525689-98322900-9c46-11eb-940f-6feac1b639d8.png)

Could potentially be related to connection timeouts as I see alot of ERROR messages in the log:
![image](https://user-images.githubusercontent.com/35863893/114526199-0b3b9f80-9c47-11eb-854f-af8690e10519.png)

Happy to help with debugging!

**Comment by perra123** [comment]
After some researching, it seems that this is caused by the Sector api reporting incorrect status.
Thus, closing.

**Comment by gjohansson-ST** [comment]
I would not mind to get the extract for the log to see what is written there as the snap tells to little
