### ISSUE TITLE
Enforce code entry?

### ISSUE THREAD

**Issue by 2357roger** [gjohansson-ST/sector#28]
Hey, 

I just installed this and it works wonderfully! With the kids in bed I don't want to try, but would you have to enter the code prior to arm or does it arm by a single press? 

Would I enforce code entry for arming and lock/unlock by leaving the code blank in config?

**Comment by 2357roger** [comment]
I understand the reason and the need for the code to be predefined but personally I prefer having to enter the code at all times, except for status obviously. 

Allowing your voice assistant to disable the alarm at best with a voice match "security" sounds like a terrible idea to me.

I would definitely support making it an option in config whether the code entry should be enforced in gui for arm/disarm/lock/unlock.

**Comment by gjohansson-ST** [comment]
If you leave the pin code empty (it's available by options) you need to supply the code.
Thereby closing this issue as resolved.
