### ISSUE TITLE
Breaks app funcionality?

### ISSUE THREAD

**Issue by daunjo** [gjohansson-ST/sector#29]
It seems this integration breaks funcionality of Sectors app. If I log in to the integration push notifications stop working, and the history in the app stops working properly. 
Anyone else having issues?

**Comment by gjohansson-ST** [comment]
There is something in the backend at Sector which makes this as a problem. It's been there from day 1 and not possible to fix.
However you would have history and can make notification in HA instead.

**Comment by klercker** [comment]
I’ve had to reset the password once, when there had been login connection
issues (or was it wrong password - don’t quite remember) and the
integration retried a bit too many times making the API login void. Since
that one time it’s been running without issue in both HA and app.
