### ISSUE TITLE
pin code is a bit funky

### ISSUE THREAD

**Issue by dogmatic69** [gjohansson-ST/sector#30]
Not quite worked it all out but it seems like I can only arm/disarm with the pin code configured at install. That is not so great as everyone in the house has their own pass code meaning they cant use HA to disable the alarm.

Also I don't find a place in the UI (or anywhere) to change the configured pin.

Why must the code compare the entered pin to the configured pin anyway, just send the disarm command with what ever pin is provided.

**Comment by gjohansson-ST** [comment]
Sorry for a late reply but I will change the code so one can choose to use a pin or not to arm/disarm. Will come back

**Comment by dogmatic69** [comment]
I changed it like this and works ok. Idea is that there is no need for a code to lock (that is how the control panel works, you just press arm home / away). 

To disarm it requires a code, but will use whatever is entered. If the code is wrong sector will handle it. 

```

    async def async_alarm_arm_home(self, code=None):
        _LOGGER.debug("Trying to arm home Sector Alarm")
        result = await self._hub.triggeralarm("partial", code=(code or self._code))
        if result:
            _LOGGER.debug("Armed home")
            self._state = STATE_ALARM_ARMED_HOME
            await self.coordinator.async_refresh()

    async def async_alarm_disarm(self, code=None):
        _LOGGER.debug("Trying to disarm")
        result = await self._hub.triggeralarm("disarm", code=code)
        if result:
            _LOGGER.debug("Disarmed Sector Alarm")
            self._state = STATE_ALARM_DISARMED
            await self.coordinator.async_refresh()

    async def async_alarm_arm_away(self, code=None):
        _LOGGER.debug("Trying to arm away")
        result = await self._hub.triggeralarm("full", code=(code or self._code))
        if result:
            _LOGGER.debug("Armed away Sector Alarm")
            self._state = STATE_ALARM_ARMED_AWAY
            await self.coordinator.async_refresh()
```

**Comment by dogmatic69** [comment]
Updated to beta16 and I've configured with the code but disarming now works without a code. IMO it should be possible to arm without a code but disarm should explicitly requite entering the pin.

**Comment by gjohansson-ST** [comment]
I decided to go for on or off on this one so if a code is supplied in config options then arming/disarming can be without code supplied.
Likewise if no code is set in options a code needs to be supplied every time.

Everyone is going to want different so feel free to alter the code for your fit as with your example above.
