### ISSUE TITLE
Trigger manual sync

### ISSUE THREAD

**Issue by daniarv** [gjohansson-ST/sector#31]
Hi,

Do you know if it's possible to trigger a sync manually?
I have set the integration to sync every 15 minutes but I would also like to trigger a sync manually from example an automation.

Is this something that can be implemented or do you know if it's possible to already trigger it through an automation?

Thank you for this great integration :)

**Comment by dogmatic69** [comment]
There does not seem to be any code in the repo currently to trigger a manual sync.

**Comment by gjohansson-ST** [comment]
From HA 2016.6 you should be able to in system options for the integration turn off polling and then use the homeassistant_update_entity service to manually poll. https://www.home-assistant.io/blog/2021/06/02/release-20216/#disable-polling-updates-on-any-integration
I have not tried but it should work, please report back

**Comment by daniarv** [comment]
> From HA 2021.6 you should be able to in system options for the integration turn off polling and then use the homeassistant_update_entity service to manually poll. https://www.home-assistant.io/blog/2021/06/02/release-20216/#disable-polling-updates-on-any-integration
> I have not tried but it should work, please report back

Thanks for pointing that out!
Will try in and report back :)

**Comment by daniarv** [comment]
A follow up:

I have now tried to use homeassistant.update_entity (Call service) against the following entities and they seems to update manually:

alarm_control_panel.sector_alarm_manoverpanel
lock.sector_alarm_yale_doorman

It doesn't seem to be working when calling the service again the temperature sensor (sensor domain) but that's fine by me as the most important is the lock and alarm state.

**Comment by gjohansson-ST** [comment]
I think the temp sensors should be fine too. There is a special check for those as the api is extremely slow it doesn't check them as frequently as the rest. 
Thanks for responding back on this.

**Comment by gjohansson-ST** [comment]
Closing this as it's solved with the built in HA feature
