### ISSUE TITLE
Sector Alarm timing out

### ISSUE THREAD

**Issue by daniarv** [gjohansson-ST/sector#32]
Hi,

Very often I get this error message in my logs:
_2021-07-19 07:08:05 ERROR (MainThread) [custom_components.sector] Timed out when connecting to Sector Alarm_
In this case the error message has came up 37 times the last two days...

I think it might be related to that Sector Alarms website sometimes takes incredible long time to load all states and then your plugin gives up because it takes too long.

Do you think this is the case and if so, is it possible to increase the time before the plugin gives up to get all states from Sector Alarm?

**Comment by gjohansson-ST** [comment]
Hi

Yes, especially when you use the temp sensors the api is incredibly slow in responding and therefore there is a built in way that it finally gives up hence you get those messages in the log.
It's nothing to be bothered about and it will just get them in the next cycle instead which is 60 seconds (5 min for temp sensors) if you have not adjusted it yourself.
No point in increasing the timeout, no added value in doing that.
