### ISSUE TITLE
Temps removed or am I blocked?

### ISSUE THREAD

**Issue by Ubiquitous-X** [gjohansson-ST/sector#33]
Today the temp sensors in my cameras went unavailable. I went to the app and "my pages" and saw that they are no longer showing up at all.

If it works for others I probably got blocked and got it removed by Sector. I had 180 secs polling time the last few months without problem until today.

So before contacting Sector I am asking if it works for others or if the feature has been removed for everyone or just me.

**Comment by gjohansson-ST** [comment]
The connection to sector is using the same api as the phone app is doing so if they are missing there, they would not show up in HA either.
Sounds to me as they have been removed from your configuration and thereby I would be more nervous about the cameras to be honest.
I'm not using Sector anymore so can not confirm if this is for you only so let's see if you get any response from someone else too.

**Comment by klercker** [comment]
I think there has been problems with the API (or perhaps the data sources
behind it) for a while. Cameras and sensors come and go in the app and
 “pushed” (automatic) updates are sketchy. When you get looked out of your
account due to too much API use everything’s blocked and quite obvious.

**Comment by Ubiquitous-X** [comment]
Today the temp sensors appeared again in the Sector app, and the integration could pick them up again.

Something is going on. If they disappear again I might contact Sector, as the whole camera might be offline at their side.
