### ISSUE TITLE
Option to enable/disable polling of temperature sensors

### ISSUE THREAD

**Issue by iZac85** [gjohansson-ST/sector#35]
Thanks for developing this promising plugin! 

Sadly I get issues with my alarm (problems with status in the Sector Alarm app, notifications of alarm turned on/off many times per day, even though the status of the alarm has not changed, issues with my Yale lock taking too long time to communicate with the alarm). I had a Sector Alarm technician here today and he found no issues with my alarm unit and suggested the Hass integration is probably the cause of all my issues, especially since I did not have them before adding this integration.

One thing I thought about was to change polling rate to like 5 minutes or more, which might work but would be less optimal for automations based upon the alarm status... 

Another thought was that maybe the issue would go away if the temperature data would be excluded from the polling. That is why I'm writing this feature request here, to ask if such a feature would be possible to add? :)

**Comment by Ubiquitous-X** [comment]
I used to have 10 minutes polling and got timed out a few times a day. (I mostly use the temp sensors, and no automation based on the alarm status for the very reason they don´t allow frequent polling.) During the time out strange things happen with the Sector Alarm app as well.

Today I got a phone call from Sector Alarm. They saw I had a home automation and they asked me to increase the polling frequency even more. The representative said 30 minutes is what they accept. Sadly that makes any automation based on the alarm status not realistically possible. Or the alarm status useful at all in Home Assistant to be fair.

We didn´t talk much more, as the customer service didn´t have detailed technical knowledge, but I did ask if it was possible to have different polling times for the alarm and the temp sensors. She said it was not possible, as everything is pulled in the same call.

**Comment by iZac85** [comment]
Roger! So it seems that Sector Alarm currently is making it hard for us Home automators 😢 

If the polling is set to e.g. 30 mins, is it still possible to request for example activation/deactivation of the alarm or to lock/unlock a lock? Or would that request also take 30 mins to progress?

**Comment by Ubiquitous-X** [comment]
From what I can understand you can activate/deactivate the alarm and locks as much as you want. That is no different than using the Sector Alarm app. It is the polling for status that is restricted.

**Comment by iZac85** [comment]
That's good at least! From my point of view, the option to disable polling of temperature sensors is still a desired one. For the following reasons:

- I already have other temp sensors in all rooms where I have Sector Alarm sensors and I don't want to have duplicate ones
- I imagine that requesting temperature values many times per day would use up the battery life of the sensors faster?
- And to reduce the load of the alarm (even if polling is set to 30 mins)

**Comment by gjohansson-ST** [comment]
Hi. If you remove the integration and add it again you can choose then to not use the temp-sensors.
It would lower the load on the polling significantly as getting the temp's takes the longest time of all status checking.
No further options available.

**Comment by iZac85** [comment]
Thanks for the tip, I did just that :)
