### ISSUE TITLE
No "Sector Alarm" integration found

### ISSUE THREAD

**Issue by bjornand1** [gjohansson-ST/sector#36]
Hi, I am trying to get this integration to work and I have been following the optional installation method. After having placed the 11 files in "custom_components/sector" and restarted Home Assistant, I try to add the integration, but nothing called Sector is found. Any advice on how to proceed?

**Comment by gjohansson-ST** [comment]
No really more than checking that the path to the files is really correct and perhaps then a new restart.
I know in some browsers (e.g. Chrome) you might need to press CTRL+F5 to hard refresh the webpage or it might now be reloaded correctly even though a restart
