### ISSUE TITLE
Switch beta 0.3.4 beta 3 - option to enable swith/smartplugs missing

### ISSUE THREAD

**Issue by MrDuco** [gjohansson-ST/sector#39]
No option to enable swith/smartplugs during setup
![image](https://user-images.githubusercontent.com/57446374/144717682-3befc738-bbd3-41eb-9be4-befb4333980d.png)

**Comment by gjohansson-ST** [comment]
Is that really wanted? Why would you not want to have the plugs in here?

**Comment by MrDuco** [comment]
@gjohansson-ST  u are right. Skip this just thought it should look the same but it just takes extra time and debugging.

**Comment by gjohansson-ST** [comment]
I'm also thinking just to remove the lock as option too.
The temps are terrible in updating so that's why they are in as option.
You think we remove lock too?

**Comment by MrDuco** [comment]
I think that lock can be removed!
