### ISSUE TITLE
Wasnt solved after all - I tried arming today, and it failed because "lock is not defined"

### ISSUE THREAD

**Issue by gjohansson-ST** [gjohansson-ST/sector#4]
@gjohansson-ST wasnt solved after all - I tried arming today, and it failed because "lock is not defined"

_Originally posted by @yusijs in https://github.com/gjohansson-ST/sector/issues/1#issuecomment-640590939_

**Comment by gjohansson-ST** [comment]
@yusijs

**Comment by gjohansson-ST** [comment]
@yusijs I just released a new beta to fix that issue.
Please install v0.1.7-beta and try again.

Thanks for helping

**Comment by yusijs** [comment]
It works now, but there was a bit of a delay after disarming (~30-40s), but that may just be how it is 🤷

**Comment by gjohansson-ST** [comment]
Hi

I noticed myself that there is a delay of "informing" HA that it's armed/disarmed meanwhile the actual alarm is activated almost directly. 
Was there a delay in the actual arming or just a delay of "information" to HA that it has been armed (I'm actually looking at solving the information piece to have HA react quicker).
Thanks

**Comment by yusijs** [comment]
Just updating the status - the sector app gave me a notice immediately

**Comment by gjohansson-ST** [comment]
Perfect. I created a new issue on the delay so I will get that sorted one way or another.
Thanks for the help to improve this!

Take care
