### ISSUE TITLE
No status update after upgrading to 0.34

### ISSUE THREAD

**Issue by sogjohan** [gjohansson-ST/sector#41]
After upgrading to 0.34 status update/feedback in HA stops working.
I can activate the alarm and lock the door from HA but I get no feedback/status update. The alarm looks like it's off and the door is marked as unlocked even though it's locked.
After downgrading to 0.33 everything works fine again.
I've upgraded to HA 2021.12 but no change in behaviour.

**Comment by gjohansson-ST** [comment]
This should be sorted in the latest beta just released. Give it a try and report back.

**Comment by sogjohan** [comment]
I just upgraded to 0.34 beta 11. Alarm status update seems to be working but the yale lock integration is still acting weird.
Locking works but the icon/status in HA doesn't change and unlocking has no effect on the lock.

**Comment by gjohansson-ST** [comment]
You didn't get a timeout in the logs and it works a bit later?

**Comment by sogjohan** [comment]
I've done some further testing and noticed the following:
In my HA I have a button for locking/unlocking which has been using the "toggle" function. 
When using that button now, only locking works. Nothing happens when I try to unlock.
If I change the function for the button to "Default action" the entity window opens and I have a "unlock" and "lock" button. 
If I use those both locking and unlocking works.
The status icon for the lock never updates though. It remains as unlocked no matter what state the lock is in physically.

I don't see any timeouts in the logs. this is the only message regarding Sector:
2021-12-20 11:20:19 ERROR (MainThread) [homeassistant.components.switch] Error while setting up sector platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/sector/switch.py", line 36, in async_setup_entry
for switch in switches:
TypeError: 'NoneType' object is not iterable

**Comment by gjohansson-ST** [comment]
Found it. Will release new beta shortly

**Comment by sogjohan** [comment]
I just upgraded to 0.34 beta 12 and now everything seems to work as intended. Thanks for the fix :)
(I don't know if it's "by design" but I think that it's noticeably slower than on 0.33.)

**Comment by sogjohan** [comment]
I've always had the refresh time set to 60 seconds so no change there.
I find it slower for HA to update the status for the alarm and lock than on 0.33. 
I can hear the lock activating physically but it takes longer time for HA to display the change.

**Comment by gjohansson-ST** [comment]
I was previously writing the state with the action so then it would go much faster but HA would not know if the lock was actually locked or not. So since then I changed it so it now waits for the api to return the information.
I was thinking to put in the write-state function again but then one can think the lock is locked but actually it isn't because a malfunction or something.
What you think is the better approach?

**Comment by gjohansson-ST** [comment]
I did anyway now change so it should change the state immediately.
I also changed the general updating so I would be happy if you can trigger a state change outside of HA just to see the updating of state happens as it should (open the doorlock or something manually).
Thanks

**Comment by sogjohan** [comment]
updated to beta 13
The status updates faster now but if the slow way is more "correct" I have no problems learning to live with that ;)
I get this error in log when locking/unlocking (but it still works):
2021-12-20 20:00:11 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140636250184432] object NoneType can't be used in 'await' expression
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
await result
File "/config/custom_components/sector/lock.py", line 123, in async_lock
await self.async_write_ha_state()
TypeError: object NoneType can't be used in 'await' expression

I also tried opening the lock manually but it had no effect in HA. It still says "locked"

**Comment by gjohansson-ST** [comment]
I think that's all sorted now. --> New beta
So the lock should react immediately on your locking/unlocking and likewise if you do a manual test you should see the state changes as the api is polled.
Thanks for testing

**Comment by gjohansson-ST** [comment]
Solved in latest release v0.3.4
