### ISSUE TITLE
Getting false armed home/disarmed triggers

### ISSUE THREAD

**Issue by hnrk** [gjohansson-ST/sector#42]
Since a while back (don't know for how long though) I get false armed home or disarm triggers. There is no actual arming or disarming of the alarm system (the log in the Sector Alarm app is clean). I don't see anything strange in the logs in HA either.

**Comment by gjohansson-ST** [comment]
Can you show me a printscreen from your logbook page of the entity from the period and also type here your automation.
Thanks

**Comment by hnrk** [comment]
![Screenshot from 2021-12-20 12-12-26](https://user-images.githubusercontent.com/581487/146759409-78112f81-a1e1-4953-a40d-2818b92cb358.jpg)

The automation:
`- id: '1639816675679'
  alias: '[TEST] Sector alarm debug'
  description: ''
  trigger:
  - platform: device
    device_id: ea12316c77960359864c5d4ad89c9d21
    domain: alarm_control_panel
    entity_id: alarm_control_panel.sector_alarmpanel_XXX
    type: disarmed
  - platform: device
    device_id: ea12316c77960359864c5d4ad89c9d21
    domain: alarm_control_panel
    entity_id: alarm_control_panel.sector_alarmpanel_XXX
    type: triggered
  condition: []
  action:
  - service: notify.mobile_app_pixel_5
    data:
      title: HA Sector alarm, triggered
      message: '{{ states("alarm_control_panel.sector_alarmpanel_XXX")}}'
  mode: single`

**Comment by gjohansson-ST** [comment]
This is very strange.
Is it possible that you can turn on debugging on the component and when you see this happen again then post the relevant section from the log to me.
Put below in your config yaml file and restart
`
logger:
  default: warning
  logs:
    custom_components.sector: debug
`

**Comment by hnrk** [comment]
At the end it is seems to looping like crazy. 
Note: the self._changed_by is always the same though I've replaced it here.

[ha_sector_log.txt](https://github.com/gjohansson-ST/sector/files/7751211/ha_sector_log.txt)

**Comment by gjohansson-ST** [comment]
It's not looping but it does go an fetch info every ~60 seconds so of course it fill the log.
Remove those lines for now so you don't flood you log.

The api is reporting a status 2 which means ARMED_HOME so actually what you see above is correct.
But I will modify the code slightly to get more information and put a new beta so you can run it and send me a log again. Given you say the alarm is never armed it's very surprising.
Hope you're ok with testing

**Comment by hnrk** [comment]
Sure thing, I'm ok with testing.

It's weird because it's more than a week ago since anyone used the alarm, still I get these triggers. I don't know yet, but it seems to be more activity at night.

**Comment by gjohansson-ST** [comment]
Perfect. I just made beta15 so install it, ensure the logging in config yaml is there and restart.
Wait for the notification to hit you and send me the logs.

Thanks

**Comment by hnrk** [comment]
So easiest way to install beta15 is to overwrite the custom_componets/sector with the latest commit?

**Comment by gjohansson-ST** [comment]
I was just assuming you were using HACS to manage it.
Go to releases and download the source.zip and replace the content in your custom_components/sector folder
https://github.com/gjohansson-ST/sector/releases/tag/v0.3.4-beta15

**Comment by hnrk** [comment]
[ha_sector_log_beta15.txt](https://github.com/gjohansson-ST/sector/files/7756709/ha_sector_log_beta15.txt)

I've seen at least 2 false triggers which should show up inte log excerpt.

**Comment by gjohansson-ST** [comment]
Very interesting. It's reporting itself as offline so I assume behind the scenes it reset's itself to status 2 if it can't "communicate".
I can work with that logic to not change status unless it's online.
Will get a fix in.

**Comment by hnrk** [comment]
Interesting!

I'll try out the new version when you're done. :-)

**Comment by gjohansson-ST** [comment]
beta16 is just released.
Would be good if you can manually (physical panel) turn on armed_home after some time and see that it updates the status of the alarm_panel in HA. Just to be sure it's still pulling updates correctly.

**Comment by hnrk** [comment]
Everything seems to be working just fine now. Nice!
