### ISSUE TITLE
Update through HACS results in missing alarm panel sensor

### ISSUE THREAD

**Issue by dogmatic69** [gjohansson-ST/sector#46]
I've upgraded a couple times and each time I've had to recreate the integration with numerous restarts to get it working again.

## expected

After upgrading the alarm sensor still exists and works

## actual

sensor does not exist

## steps

- upgrade
- reboot
- notice sensor is not available
- delete it
- recreate integration, enter all details again
- sensor is back

**Comment by gjohansson-ST** [comment]
Are you speaking specifically about the temp-sensors?

**Comment by dogmatic69** [comment]
The alarm panel, seems like the whole integration.

**Comment by gjohansson-ST** [comment]
Actually now if you have it running again there is nothing I can do so I will close the issue. But the whole thing seems very odd as there has not been any change in it that would make this behavior.
If it happens again before doing anything make sure you take out the relevant part of the log, there should be several errors in it if it can't load properly etc.
Thanks
