### ISSUE TITLE
Timed out when connecting to Sector

### ISSUE THREAD

**Issue by donjohann** [gjohansson-ST/sector#55]
Since about a  week ago I keep getting this problem. Seems like I get more timed out than successful connections. But every now and then I get the alarm state.

_Logger: custom_components.sector
Source: custom_components/sector/__init__.py:445 
Integration: Sector Alarm ([documentation](https://github.com/gjohansson-ST/sector/blob/master/readme.md), [issues](https://github.com/gjohansson-ST/sector/issues)) 
First occurred: 4 maj 2022 22:04:56 (85 occurrences) 
Last logged: 08:47:30

Timed out when connecting to Sector_

**Comment by Ubiquitous-X** [comment]
What is your polling rate?

Sectors customer service says they accept 1 per hour. You can get away with once every 30 minutes, but anything under that will for sure lead to a soft ban

**Comment by gjohansson-ST** [comment]
I had the same issue and in most cases it's due to the temp-sensors so if you have those enabled then disable them and find a better way to get temp than those.

btw; would never ask any customer service for a polling rate. I think max once a minute should be fine in general.

**Comment by dogmatic69** [comment]
I have once a minute for over a year now and can tell you these timeouts are due to the service being down. It's constant and random.

**Comment by gjohansson-ST** [comment]
Closing this as it's a constant issue with Sector Alarm and one just have to accept that you get timeout from time to time...
