### ISSUE TITLE
Deprecated `async_get_registry`

### ISSUE THREAD

**Issue by Olen** [gjohansson-ST/sector#59]
After update to 2022.6.1
```
WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for sector using this method at custom_components/sector/__init__.py, line 135: device_registry = await dr.async_get_registry(hass)
```

**Comment by robinsmidsrod** [comment]
Here's the entire log entry, in case it helps:

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 16:11:04 (1 occurrences)
Last logged: 16:11:04

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for sector using this method at custom_components/sector/__init__.py, line 125: device_registry = await dr.async_get_registry(hass)
```

**Comment by gjohansson-ST** [comment]
That's fine. I will check it shortly

**Comment by gjohansson-ST** [comment]
@robinsmidsrod if you know how to can you run this script and provide the output so I get some fresh api data to work with.
Of course you need to redact sensitive data before you send it to me.
https://github.com/gjohansson-ST/sector/blob/master/api-info/api_info.py

**Comment by robinsmidsrod** [comment]
Here's the info from the script with panelid and serial numbers redacted. I don't have any locks, which is why that last call fails.

```
2022-06-04 18:32:48.904347
2022-06-04 18:32:49.796234
FULLSYSTEMINFO
{
    'Panel': {
        'PartialAvalible': True,
        'PanelQuickArm': False,
        'PanelCodeLength': 4,
        'LockLanguage': 0,
        'SupportsApp': True,
        'SupportsInterviewServices': True,
        'SupportsPanelUsers': True,
        'SupportsTemporaryPanelUsers': True,
        'SupportsRegisterDevices': True,
        'CanAddDoorLock': False,
        'CanAddSmartPlug': False,
        'HasVideo': False,
        'Wifi': {
            'WifiExist': False,
            'Serial': ''
        },
        'PanelId': '0******4',
        'ArmedStatus': 'disarmed',
        'PanelDisplayName': 'Hjemme',
        'StatusAnnex': 'unknown',
        'PanelTime': '2022-06-04T09:28:24.07',
        'AnnexAvalible': False,
        'IVDisplayStatus': False,
        'DisplayWizard': False,
        'BookedStartDate': '0001-01-01T00:00:00',
        'BookedEndDate': '0001-01-01T00:00:00',
        'InstallationStatus': 3,
        'InstallationAddress': None,
        'WizardStep': 0,
        'AccessGroup': 0,
        'SessionExpires': '0001-01-01T00:00:00',
        'IsOnline': False
    },
    'Locks': [],
    'Smartplugs': [],
    'Temperatures': [{
            'Id': None,
            'Label': 'gang',
            'SerialNo': '24******77B',
            'Temprature': '',
            'DeviceId': None
        }, {
            'Id': None,
            'Label': 'stue',
            'SerialNo': '24******07B',
            'Temprature': '',
            'DeviceId': None
        }, {
            'Id': None,
            'Label': 'ir kontor',
            'SerialNo': '24******E3D',
            'Temprature': '',
            'DeviceId': None
        }, {
            'Id': None,
            'Label': 'ir serverrom',
            'SerialNo': '24******055',
            'Temprature': '',
            'DeviceId': None
        }
    ],
    'Cameras': [],
    'Photos': [],
    'Access': ['History', 'Directions', 'SecurityQuestion', 'ContactPersons', 'AlarmSystemSettings', 'LockSettings', 'SmartplugSettings', 'Photos', 'Smartplugs', 'Cameras', 'CameraSettings', 'PanelUsers', 'AddProducts', 'AppUserSettings', 'PreInstallationSettings', 'Wifi', 'Booking', 'ChangeVideoConsent']
}
2022-06-04 18:32:50.075675
GetPanelStatus
{
    'IsOnline': False,
    'StatusTime': '2022-06-04T09:28:24.07',
    'Status': 1,
    'AnnexStatus': 0
}
2022-06-04 18:32:50.253910
GetTemperatures
[{
        'Id': None,
        'Label': 'gang',
        'SerialNo': '24******77B',
        'Temprature': '27',
        'DeviceId': None
    }, {
        'Id': None,
        'Label': 'stue',
        'SerialNo': '24******07B',
        'Temprature': '27',
        'DeviceId': None
    }, {
        'Id': None,
        'Label': 'ir kontor',
        'SerialNo': '24******E3D',
        'Temprature': '28',
        'DeviceId': None
    }, {
        'Id': None,
        'Label': 'ir serverrom',
        'SerialNo': '24******055',
        'Temprature': '24',
        'DeviceId': None
    }
]
2022-06-04 18:33:16.418170
Funkar inte
GetLockStatus
Traceback (most recent call last):
  File "./api_info.py", line 118, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "./api_info.py", line 98, in main
    print(GetLockStatus)
UnboundLocalError: local variable 'GetLockStatus' referenced before assignment
```

**Comment by gjohansson-ST** [comment]
Hi @robinsmidsrod 
Given it seems it is slightly different for you can you also check what is written [here](https://github.com/gjohansson-ST/sector/issues/56) and check from your side.

Mainly want to make sure the endpoints are the same as he is mentioning so I don't solve someone's issue but makes one for someone else (e.g. you in this case 😄 )

**Comment by robinsmidsrod** [comment]
@gjohansson-ST Here's the endpoints and data from a normal login session using the browser attached. I'm not sure where `__RequestVerificationToken` was set, but I do notice it is the same for all XHR requests (in a single page load).

Endpoints:
* POST https://mypagesapi.sectoralarm.net/User/Login (302 form redirect to HTML)
* GET https://mypagesapi.sectoralarm.net/Settings/GetTextByCulture?lang=nb-NO (JSON)
* GET https://mypagesapi.sectoralarm.net/User/GetUserInfo/ (JSON)
* GET https://mypagesapi.sectoralarm.net/Panel/GetPanelList/ (JSON)
* POST https://mypagesapi.sectoralarm.net/Panel/GetOverview/ (JSON)

[sector_debug.txt](https://github.com/gjohansson-ST/sector/files/8851455/sector_debug.txt)

**Comment by gjohansson-ST** [comment]
Thank you @robinsmidsrod very good data provided.
One last thing can you also expand the temperatures and see the request you get then. Just want to confirm these requests has not changed.

**Comment by robinsmidsrod** [comment]
@gjohansson-ST When I expand the temperature panel I just get a message stating that temperatures can't be fetched if the system isn't connected to the internet, and no API requests are sent. My system uses intermittently connected GSM communication. I do get temperatures in Home Assistant, so apparently the temperature is available occasionally using the current method. Using version v0.3.5-beta1.

**Comment by gjohansson-ST** [comment]
Hi @robinsmidsrod 
I didn't notice before but the endpoints you sent are not the api ones but the websites it's loading. I think you should be able to see in developer tools which api end-point is used.
Also can you give a try with temp again?

**Comment by robinsmidsrod** [comment]
@gjohansson-ST Those where the JSON endpoints that I saw in developer tools when the website was loading. I did not see any /api/v2/... URLs.

I don't know how to trigger my sector hub to be online so that the temperatures are readable, unfortunately. If you have any idea how to make them readable, please enlighten me.

**Comment by gjohansson-ST** [comment]
Ok. I wonder here if Sector is actually rolling out a new version as I got also data from another person with the api endpoint but with new endpoints not seen before for some off the data. Not going for those now as it would probably destroy for others.
Then we can skip the rest too as I think I have most covered now. I will release a new beta shortly so of course appreciate you testing.
