### ISSUE TITLE
Make component show up in Integration list, with configuration UI

### ISSUE THREAD

**Issue by klercker** [gjohansson-ST/sector#8]
This integration is looking really good, especially being based on what seems to be(?) an SA API. Great work!

It would be great to have the integration and configuration show up in the integrations UI. From what I can gather this is mainly a manifest issue. I have forked the project and will take a peek at this. Who knows, a PR might be forthcoming? It's my first time developing an HA component (although I have 35 odd years of experience in programming), so plz have patience :)

**Comment by klercker** [comment]
After looking into it a bit more, there is quite a bit more to it than creating manifests, but still looks doable.

**Comment by gjohansson-ST** [comment]
Implemented in v0.2.0-beta3
Closed with final release

**Comment by klercker** [comment]
Awesome, looks great!
