### ISSUE TITLE
Config entry 'email@address' for sector integration could not authenticate: None

### ISSUE THREAD

**Issue by Olen** [gjohansson-ST/sector#94]
**Describe the bug**
With latest betas, I looks like I need to reauthenticate after each restart (or maybe only after each update) 

**Version**
v0.3.5-beta10

**Expected behavior**
Authentication details should be reused on subsequent restarts/updates 

**Additional context**
The error-message is in the topic
```
Config entry 'email@address' for sector integration could not authenticate: None
```

**Comment by gjohansson-ST** [comment]
Have you tried to remove it and add it again?

**Comment by einarsi** [comment]
Almost a week and no new notifications to reconfigure. So it seems to be stabilized for now.

**Comment by einarsi** [comment]
It happened again this morning.

```
This error originated from a custom integration.

Logger: custom_components.sector
Source: helpers/update_coordinator.py:197 
Integration: Sector Alarm (documentation, issues) 
First occurred: June 17, 2022, 15:31:08 (13 occurrences) 
Last logged: 08:43:07

Timeout fetching sector_api data 
```
and
```
This error originated from a custom integration.

Logger: custom_components.sector
Source: custom_components/sector/coordinator.py:143 
Integration: Sector Alarm (documentation, issues) 
First occurred: 09:08:43 (1 occurrences) 
Last logged: 09:08:43

Unexpected error fetching sector_api data: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/sector/__init__.py", line 91, in async_update_data
    await api.fetch_info()
  File "/config/custom_components/sector/coordinator.py", line 143, in fetch_info
    self.api_data[panel]["codelength"] = response_getpanel.get(
AttributeError: 'NoneType' object has no attribute 'get'
```
The notification states that it happened 10 hours ago, so I am not sure which of the two error messages was the last before I had to reauthenricate (it is now 18:54).

**Comment by gjohansson-ST** [comment]
Thanks for providing feedback. I have not managed to get to it yet.
Regarding the auth-problem I think perhaps it mistakes an auth error with something else. It's triggered now on a keyword. I will try to get the whole text to the log so you can tell me what it says.

btw: should be enough restarting the integration I think or do you really need to restart HA?

**Comment by einarsi** [comment]
Thanks for the update. I will try to reload the integration the next time this happens. 

Also, an observation that may not be relevant or even correct: I am pretty certain that every time it has failed like this it has been in state armed_away. A best effort calculation based on 4 occurrences gives a statistical probability of (9/24)^3*(4/24) ~ 1%, which means it is rather unlikely to be just a coincidence. But in case you see any kind of connection to the rest of the code it may potentially be helpful. Or just confusing and misleading ;)

**Comment by Olen** [comment]
FWIW I don't think mine has ever been "armed_away". But on the other hand, here it seems to only happen at HA restart.  
My HA-container has been running for 9 days now, and I have not been asked to reauthenticate while it is running.
So these might be different - but probably related - issues.
 
I'll try to remove and re-add the Sector-integration next time I upgrade HA, and see if that makes any differende.

**Comment by Rilleboy** [comment]
After every restart of my HA i always have to enter my username and password again in the config....

**Comment by Olen** [comment]
Tried to remove the integration. and add it back, but I still need to add my email and password after every restart.

**Comment by Olen** [comment]
See #100 which I believe is the same issue (or the same underlying problem)

**Comment by gjohansson-ST** [comment]
Solved with https://github.com/gjohansson-ST/sector/releases/tag/v0.3.5
