### ISSUE TITLE
Integrations is stuck on "Waiting"

### ISSUE THREAD

**Issue by Henke19822** [gjohansson-ST/sector#97]
**Describe the bug**
Integration is being installed and everything seems to work, but Device/Entity just states "Waiting"

**Version**
V.0.3.4

**Expected behavior**
A correct status of alarm is being fetched, and changed accordingly

**Additional context**
-

**Comment by gjohansson-ST** [comment]
Should be fixed now with https://github.com/gjohansson-ST/sector/releases/tag/v0.3.5-beta11

**Comment by gjohansson-ST** [comment]
Solved with https://github.com/gjohansson-ST/sector/releases/tag/v0.3.5
