### ISSUE TITLE
Integration doesn't work in 2022.7.6

### ISSUE THREAD

**Issue by DanielOrneling** [gjohansson-ST/sector#99]
I get this error when trying to set up the integration in 2022.7.6 tjat i just updated to.

Logger: homeassistant.components.sensor
Source: custom_components/sector/sensor.py:41
Integration: Sensor (documentation, issues)
First occurred: 07:35:21 (1 occurrences)
Last logged: 07:35:21

Error while setting up sector platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/sector/sensor.py", line 41, in async_setup_entry
    for sensor in thermometers:
TypeError: 'NoneType' object is not iterable

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/sector/__init__.py:534
Integration: Sector Alarm (documentation, issues)
First occurred: 07:35:21 (1 occurrences)
Last logged: 07:35:21

Error setting up entry sa_02723167 for sector
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/sector/__init__.py", line 138, in async_setup_entry
    identifiers={(DOMAIN, "sa_hub_" + str(api.alarm_id))},
  File "/config/custom_components/sector/__init__.py", line 534, in alarm_id
    return self._panel["PanelId"]
TypeError: list indices must be integers or slices, not str

Any idea about this issue?

**Comment by dogmatic69** [comment]
I'm running the same and it works, try delete and recreate the integration. I had some upgrade issues along the way due to changes in the backend

**Comment by gjohansson-ST** [comment]
Try with the latest beta as I can see it's a pretty old version https://github.com/gjohansson-ST/sector/releases/tag/v0.3.5-beta11
I will close this in meantime as it's duplicate from many others.
